[FEAT] 마니또 진행 화면, 이미지 추가
DeveloperAcademy-POSTECH/MC2-Team5-Firefighter pull request #171
Opened 2022-08-31 07:57 UTC by coby5502

## 🟣 관련 이슈
#170 

## 🟣 구현/변경 사항 및 이유
진행 중인 마니또 화면에서, 이미지들을 삽입하였습니다.

## 🟣 PR Point

## 🟣 참고 사항
![Simulator Screen Shot - iPhone 13 - 2022-08-31 at 16 54 08](https://user-images.githubusercontent.com/57849386/187624117-c44ab3e4-10d7-40fd-8fff-61bb640cc3d1.png)

2022-08-31 10:26 UTC, YoonAh-dev approved these changes
굿굿!

2022-08-31 10:52 UTC, MMMIIIN commented on Manito/Manito/Screens/Detail-Ing/DetailIngViewController.swift
> +        listIconView.image = ImageLiterals.icList
p4;

뭔가 `render`에 정의되는게 조금은.. 걸리는데, `configUI`로 빼는건 어떨까요 ??
제가 생각한 `render`는 레이아웃 관련 함수라 생각했고, `configUI`는 view관련 역할을 하는 함수라 생각했습니다 !
큰 차이는 없지만 코드스타일을 통일하기 위함입니다 !

2022-08-31 13:01 UTC, dangsal commented on Manito/Manito/Screens/Detail-Ing/DetailIngViewController.swift
> +        listIconView.image = ImageLiterals.icList
저도 동의합니다옹

2022-08-31 13:02 UTC, dangsal approved these changes
케미가 달아주신거만 부탁드려용~

2022-08-31 13:23 UTC, YoonAh-dev commented on Manito/Manito/Screens/Detail-Ing/DetailIngViewController.swift
> +        listIconView.image = ImageLiterals.icList
동의합니다~!

2022-08-31 13:23 UTC, dangsal commented
치소치소!!

2022-08-31 13:23 UTC, YoonAh-dev commented
어푸르브 취소 취소~

2022-09-01 06:12 UTC, MMMIIIN requested changes
혹시 바로 머지될까 리퀘스트 남기겠습니다 ~

2022-09-01 11:47 UTC, coby5502 commented on Manito/Manito/Screens/Detail-Ing/DetailIngViewController.swift
> +        listIconView.image = ImageLiterals.icList
[09462c9](https://github.com/DeveloperAcademy-POSTECH/MC2-Team5-Firefighter/pull/171/commits/09462c94f626fd6449f0b61c159b63c5c331819f)
감사링

2022-09-01 11:52 UTC, MMMIIIN approved these changes
수고하셨습니다 ~~ ^_______^

2022-09-04 03:59 UTC, YoonAh-dev commented
코비 머지하셔도 됩니당

2022-09-04 06:17 UTC, merged