[FEAT] 쪽지 뷰에서 사진 저장 버튼을 눌렀을 때 사진이 저장되는 기능을 구현했습니다.
DeveloperAcademy-POSTECH/MC2-Team5-Firefighter pull request #341
Opened 2022-11-08 07:52 UTC by YoonAh-dev

## 🌁 Background

쪽지 뷰에서 사진을 저장할 수 있으면 좋겠다는 사용자 요청이 있어서 사진 저장 기능을 추가했습니다.

## 👩‍💻 Contents

쪽지 뷰에서 사진 저장 버튼(ic_save)을 눌렀을 때 사진이 저장되는 기능을 구현했습니다.

### ➰ PHPhotoLibrary를 사용해서 Image를 갤러리에 저장했습니다.

PHPhotoLibrary 메소드 중에 `performChanges`라는 메소드가 있습니다. 해당 메소드 내부에서는 변경을 수행합니다. 항상 `performChanges` 블록에서 해야할 일은 request 를 만드는 것입니다. 생성, 삭제, 변경 뭐가 되었든간에 request 를 만들면 됩니다.

```swift
PHPhotoLibrary.shared().performChanges({
                PHAssetChangeRequest.creationRequestForAsset(from: image)
            }, completionHandler: { (success, error) in
                DispatchQueue.main.async {
                    if success {
                        self?.makeAlert(title: "저장 성공", message: "사진을 앨범에 저장했어요.")
                    } else if let error = error {
                        Logger.debugDescription(error)
                        self?.makeAlert(title: "오류 발생", message: "사진을 저장할 수 없습니다.")
                    }
                }
          })
```

* 저는 performChanges 내부에서 이미지를 저장하는 메소드를 불러줬습니다. 해당 메소드는 performChanges 내부에서만 수행할 수 있습니다. 
   <img width="644" alt="스크린샷 2022-11-08 오후 4 39 16" src="https://user-images.githubusercontent.com/55099365/200503014-c161f8fc-05f6-4c59-9a77-c2bde1bc6757.png">

* **performChanges 내부에서만 수행할 수 있다는 게 무슨 말인가요?**
  
   <img width="1081" alt="스크린샷 2022-11-08 오후 4 49 59" src="https://user-images.githubusercontent.com/55099365/200504994-a257f994-76d4-480c-8f76-cc6be8b4f0a7.png">
   PHAssetChangeRequest는 -[PHPhotoLibrary performChanges:] or -[PHPhotoLibrary performChangesAndWait:] 블럭 내부에서만 생성되고 사용될 수 있다고 쓰여있네요.

   만약 안에다가 `DispatchQueue.main.async { }`를 써주고 그 안에 해당 메소드를 넣으면 에러로 혼.쭐.납니다.
   <img width="715" alt="스크린샷 2022-11-08 오후 4 41 17" src="https://user-images.githubusercontent.com/55099365/200504634-f9f73b44-9179-4de1-b48c-afdacb71caa9.png">

   performChanges 내부에서만 해당 메소드를 부를 수 있다고 하네요. 네.. 알고 싶지 않았는데 알게 되어서 알려드립니다.

## ✅ Testing

쪽지 뷰에서 사진을 눌렀을 때 나타나는 `LetterImageViewController`에서 사진 저장 버튼을 누르면 사진이 저장되는 걸 확인하실 수 있습니다.

## 📱 Screenshot

**[ 사진 저장 실패 ]**

https://user-images.githubusercontent.com/55099365/200500159-dc190e08-d902-4dc0-a95f-1bbb34311c38.mp4  

**[ 사진 저장 성공 ]**

https://user-images.githubusercontent.com/55099365/200501263-7d158dad-fb0e-40d8-9f7c-d66e748e7a61.mp4

## 📝 Review Note

### ☑️ UX Writing

현재 제가 스스로 설정해둔 멘트가 3개 있습니다. 해당 멘트들이 괜찮은지 확인 부탁드립니다.

1. 앨범에 사진을 저장할 때 나오는 부분 : '애니또'가 사용자의 앨범에 접근하려고 합니다. 쪽지에 있는 사진을 앨범에 저장하세요.
2. 사진 저장 실패 : [title: "오류 발생", message: "사진을 저장할 수 없습니다."]
3. 사진 저장 성공 : [title: "저장 성공", message: "사진을 앨범에 저장했어요."]

### ☑️ Button Layout

현재 버튼 레이아웃을 할 때 위치를 어디로 잡아야할 지 몰라서 @sunchoi22 에게 물어봤더니 현재 위치가 가장 적절한 거 같다고 하셔서 close button 옆에다가 레이아웃을 잡았습니다. 다른 분들의 의견도 필요할 거 같아서 이 부분 다들 괜찮은지 확인 부탁드립니다.

<img width="363" alt="스크린샷 2022-11-08 오후 4 34 50" src="https://user-images.githubusercontent.com/55099365/200502182-51b81482-f173-49a3-9107-7dd61a635164.png">

## 📣 Related Issue

- close #340 

## 📬 Reference

https://zeddios.tistory.com/949

2022-11-08 08:17 UTC, dangsal commented on Manito/Manito/Screens/Letter/LetterImageViewController.swift
> +    private var downloadButton: UIButton = {
p1;

이 부분에서 var로 선언될 필요는 없다라고 생각합니다! 
실제로 let으로 바꿔서 빌드해도 정상적으로 작동합니다!
그래서 let 으로 바꾸는게 어떨지 제안드립니다!!

혹시 제가 모르는 이유가 있다면 설명 부탁드려욤~.~ !!

2022-11-08 08:27 UTC, dangsal commented on Manito/Manito/Screens/Letter/LetterImageViewController.swift
> +        }
카카오톡 | 슬랙 | 페이스북메신저 |
---- | ---- | ---- |
<img src = "https://user-images.githubusercontent.com/59243274/200511996-4a36cfc2-89c8-4e07-9958-e7c07dc4446c.png" witdh = "350"> | <img src = "https://user-images.githubusercontent.com/59243274/200512138-d3b00ada-c92b-4c75-82fa-30510e80f8fb.png" witdh = "350"> | <img src = "https://user-images.githubusercontent.com/59243274/200512198-ad55acc5-c99b-48ba-872f-7d68c8ed6d83.png" witdh = "350"> |

저장하기 버튼의 위치가 X버튼 옆에 있다는거에 대해 고민을 해보다가 
몇가지 리소스를 찾아봤는데 저장하기 버튼은 아래쪽에 있다라는 생각이 들었습니다!
그래서 위치에 대해서 같이 얘기해 보고 싶습니다!

2022-11-08 08:42 UTC, dangsal commented on Manito/Manito/Screens/Letter/LetterImageViewController.swift
> +        downloadButton.addAction(downloadAction, for: .touchUpInside)
p5;

PR에 적어주신 설명 덕분에 이해하기 편했습니다 감사합니다!!

그런데 혹시 버튼의 액션을 주는 addAction이 setupButtonAction에 있는데 저희가 지금까지 했던 방식과는 조금 다르다는 생가기 들었어요!

그래서 
```swift
    private lazy var downloadButton: UIButton = {
        let button = UIButton()
        button.setImage(ImageLiterals.icSave, for: .normal)
        let action = UIAction { [weak self] _ in
            self?.testAction()
        }
        button.addAction(action, for: .touchUpInside)
        return button
    }()
```

```
    private func testAction() {
        guard let image = imageView.image else {
            makeAlert(title: "오류 발생", message: "사진을 저장할 수 없습니다.")
            return
        }
        
        PHPhotoLibrary.shared().performChanges({
            PHAssetChangeRequest.creationRequestForAsset(from: image)
        }, completionHandler: { (success, error) in
            DispatchQueue.main.async {
                if success {
                    self.makeAlert(title: "저장 성공", message: "사진을 앨범에 저장했어요.")
                } else if let error = error {
                    Logger.debugDescription(error)
                    self.makeAlert(title: "오류 발생", message: "사진을 저장할 수 없습니다.")
                }
            }
        })
    }
```

요론식으로 하는건 어떨지 제안드립니다!

2022-11-08 08:44 UTC, dangsal reviewed
원하는 기능 뚝딱 만들어주셨군요! 자세한 PR에 깔끔한 코드 덕분에 항상 많이 배웁니다! 리뷰 몇개 남겼습니다! 수고하셨어요!

2022-11-08 09:10 UTC, MMMIIIN commented
SK브로드밴드 광고가 시선강탈이군요.... 하하

2022-11-08 09:20 UTC, MMMIIIN commented on Manito/Manito/Screens/Letter/LetterImageViewController.swift
> +        }
저도 왼쪽 아래가 적합하지 않을까.. 라고 생각합니다..

2022-11-08 09:25 UTC, MMMIIIN commented on Manito/Manito/Screens/Letter/LetterImageViewController.swift
> +                        self?.makeAlert(title: "오류 발생", message: "사진을 저장할 수 없습니다.")
p3;

내부의 text들을 TextLiteral에 적으면 좋을 것 같습니다 !

++ 혹시 사진 저장에 실패하는 경우는 어떤 경우인가요 ??

2022-11-08 10:08 UTC, coby5502 commented on Manito/Manito/Screens/Letter/LetterImageViewController.swift
> +    private var downloadButton: UIButton = {
ㅋㅋㅋㅋ

2022-11-08 10:09 UTC, coby5502 commented on Manito/Manito/Screens/Letter/LetterImageViewController.swift
> +        }
확실히 유저에게 익숙한 위치는 왼쪽 아래인 것 같습니다.

2022-11-08 10:11 UTC, coby5502 approved these changes

2022-11-15 03:55 UTC, YoonAh-dev commented on Manito/Manito/Screens/Letter/LetterImageViewController.swift
> +    private var downloadButton: UIButton = {
[`933f5f6`](https://github.com/DeveloperAcademy-POSTECH/MC2-Team5-Firefighter/pull/341/commits/933f5f6d91c5533914e414daa9fe59d250d8ed5b)
정신나간 코드 수정했습니다.

2022-11-15 03:59 UTC, YoonAh-dev commented on Manito/Manito/Screens/Letter/LetterImageViewController.swift
> +        }
왼쪽 아래로 변경해봤는데 괜찮나요? 모양 때문인지 저는 뭔가 어색하네요..

<img width="551" alt="스크린샷 2022-11-15 오후 12 58 58" src="https://user-images.githubusercontent.com/55099365/201823102-a91f2ea2-97b7-441e-8301-9928b307806e.png">

2022-11-15 04:07 UTC, YoonAh-dev commented on Manito/Manito/Screens/Letter/LetterImageViewController.swift
> +        downloadButton.addAction(downloadAction, for: .touchUpInside)
저는 계속 이 방식을 사용해왔는데, 따로 맞춘 적은 없어서 얘기할 필요가 있어보입니다.
<img width="1053" alt="스크린샷 2022-11-15 오후 1 05 18" src="https://user-images.githubusercontent.com/55099365/201823917-bb9e9027-a3b2-4b33-b093-6589d5c34da1.png">
<img width="633" alt="스크린샷 2022-11-15 오후 1 05 05" src="https://user-images.githubusercontent.com/55099365/201823924-482e55cd-dda0-4037-9d90-8f6629a6e75b.png">

2022-11-15 04:08 UTC, YoonAh-dev commented on Manito/Manito/Screens/Letter/LetterImageViewController.swift
> +                        self?.makeAlert(title: "오류 발생", message: "사진을 저장할 수 없습니다.")
사진 저장에 실패하는 경우는 접근 허용 문제라던지, 이미지 파일 타입을 제대로 바꾸지 못했을 때라던가, createRequestForAsset 내부에서 메소드를 돌리면서 생기는 에러들이 있는 경우에 error로 반환됩니다.

2022-11-15 04:14 UTC, YoonAh-dev commented on Manito/Manito/Screens/Letter/LetterImageViewController.swift
> +                        self?.makeAlert(title: "오류 발생", message: "사진을 저장할 수 없습니다.")
[`430a7d2`](https://github.com/DeveloperAcademy-POSTECH/MC2-Team5-Firefighter/pull/341/commits/430a7d29cd43f5bf3300e6b17f231f75de26af84)

내부 text들을 TextLiteral에 넣어뒀습니다.

2022-11-15 08:15 UTC, dangsal commented on Manito/Manito/Screens/Letter/LetterImageViewController.swift
> +        }
네에.. 조금 어색하네요.. 하나 있어서 그런가 싶네여..

2022-11-15 08:18 UTC, dangsal commented on Manito/Manito/Screens/Letter/LetterImageViewController.swift
> +        downloadButton.addAction(downloadAction, for: .touchUpInside)
네네 저번주에 얘기 쓱 했었는데 저는 쌉 납득 완료했습니다.

2022-11-15 08:33 UTC, MMMIIIN commented on Manito/Manito/Screens/Letter/LetterImageViewController.swift
> +        }
그러네요... 
![IMG_3345](https://user-images.githubusercontent.com/78677571/201869550-0c8c6232-8df2-4313-9199-d7965ba5a480.png)
인스타 그램은 왼쪽위가 X버튼이고 저장이 오른쪽에 있네요

2022-11-15 08:54 UTC, YoonAh-dev commented on Manito/Manito/Screens/Letter/LetterImageViewController.swift
> +        }
이렇게 됩니다.

<img width="400" alt="스크린샷 2022-11-15 오후 5 52 31" src="https://user-images.githubusercontent.com/55099365/201873982-59bcab72-4925-4ae8-a4ca-de477cb9853e.png">

@coby5502 
저번에 X 버튼이 왼쪽에 있는게 X 버튼이 계속 오른쪽에 있는 저희 디자인과 달라서, 통일성이 없어지는 거 같다고 했던 거 같아서요. 괜찮은가요..?

2022-11-15 10:09 UTC, MMMIIIN commented on Manito/Manito/Screens/Letter/LetterImageViewController.swift
> +        }
인스타그램 스토리를 확인해봤는데, 거기는 또 X버튼이 오른쪽에 있더라구요

2022-11-16 06:59 UTC, CreoHwan commented on Manito/Manito/Screens/Letter/LetterImageViewController.swift
> +        downloadButton.addAction(downloadAction, for: .touchUpInside)
> 네네 저번주에 얘기 쓱 했었는데 저는 쌉 납득 완료했습니다.

저도 납득하고 싶습니다... 설명 부탁드려도 될까요~~?

2022-12-19 12:17 UTC, MMMIIIN approved these changes
좋아요 !
수고하셨습니다 ^________^

2022-12-19 12:30 UTC, MMMIIIN requested changes
취소취소 !!!
<img width="797" alt="image" src="https://user-images.githubusercontent.com/78677571/208426593-0a7cf183-d275-4d41-b68d-5bbcddfb06fc.png">
요렇게 하기로 했던 것 같네요 ??

2022-12-19 12:31 UTC, dangsal commented on Manito/Manito/Screens/Letter/LetterImageViewController.swift
> +        }
이렇게 변경 부탁드릴게요!

2022-12-22 01:18 UTC, YoonAh-dev commented
변경했습니다.
<img width="551" alt="스크린샷 2022-12-22 오전 10 17 38" src="https://user-images.githubusercontent.com/55099365/209033888-517f5f6c-dc66-41a7-b02a-89c2829e41e5.png">

2022-12-22 01:19 UTC, YoonAh-dev commented on Manito/Manito/Screens/Letter/LetterImageViewController.swift
> +        }
https://github.com/DeveloperAcademy-POSTECH/MC2-Team5-Firefighter/pull/341#issuecomment-1362279635

변경했습니다.

2022-12-22 01:25 UTC, YoonAh-dev commented on Manito/Manito/Screens/Letter/LetterImageViewController.swift
> +        downloadButton.addAction(downloadAction, for: .touchUpInside)
@CreoHwan 

setupButtonAction이라는 함수를 만들어두고 내부에서 Action 세팅을 하는게 저는 변수에서 Action 세팅을 진행하는 것보다 낫다고 생각했습니다. 변수 선언을 할 때 그 내부 클로저에서 하는 일이 너무 많다는 생각이 들어서 Action를 설정하는 건 따로 빼도 괜찮지 않을까 싶더라구요.

2022-12-22 03:20 UTC, MMMIIIN approved these changes
좋습니다 !
수고하셨어요 ^_______^

2022-12-22 05:18 UTC, merged