[FEAT] 푸시알림을 눌렀을 때 해당 방의 쪽지뷰로 이동 기능 구현
DeveloperAcademy-POSTECH/MC2-Team5-Firefighter pull request #361
Opened 2023-01-09 14:44 UTC by MMMIIIN

## 🌁 Background

기존 PR(https://github.com/DeveloperAcademy-POSTECH/MC2-Team5-Firefighter/pull/353) 에서 쪽지가 왔을 때 푸시알림 기능을 구현했습니다. 하지만 푸시알림을 눌러도 그냥 앱에만 들어가지지 어떤 방에서 쪽지가 왔는지는 알 수 없습니다. 그 문제를 해결하기 위해 해당 PR을 작성하게 되었습니다 !

## 👩‍💻 Contents

마니또로부터 쪽지가 왔을 때 푸시알림이 옵니다. 그 알림을 눌렀을 때 해당 방으로 바로 이동하고, 쪽지함 화면까지 이동합니다. 
### 하지만 여기서 문제가 있었습니다. 

대뜸 쪽지함까지 갔더니 
<img src="https://user-images.githubusercontent.com/78677571/211327832-55a979db-7608-41b8-9bc2-a0df854e1cb0.jpeg" width="300">

이 화면이 떠서 저 조차도 당황스럽더라구요. 이 문제가 발생하는 이유가, 쪽지함의 Segment Controll의 기본값이 내가 마니띠에게 보낸 쪽지를 보여주는 화면이라 생긴 문제였습니다. 그래서 이 Segment를 마니띠로부터 시작하게끔 코드를 추가했습니다.

## ✅ Testing

마니또에게 쪽지를 요청하고, 푸시알림을 눌러서 앱에 들어가보세요 (애니또 릴리즈 톡방에 방을 만들어서 요청하는게 편할겁니다.)

## 📱 Screenshot

https://user-images.githubusercontent.com/78677571/211328725-624a1f4c-53fd-46c5-b498-1f5509435b31.MP4

## 📝 Review Note

view들이 너무 독립적이지 못하고 어디 한 쪽에 의존하고 있어서 꽤나 애를 먹었습니다.

1. 서버 통신 횟수를 줄이기 위해 클라쪽에서 데이터들을 전달하다보니 문제가 생겼습니다. 
예시로 `LetterViewController`의 `mission`이란 변수였는데요, 진행중인방 View(DetailIngCodebaseViewController) -> 쪽지함 View(LetterViewController) 로 이동하는 과정에서 초기화하는 방식으로 전달합니다.
처음엔 SceneDelegate에서 1. 홈 화면 2. 진행중 화면 3. 쪽지 함 화면. 이 세개를 UINavigationViewController의 스택으로 바로 쌓아서 rootView를 변경하려니 LetterViewController의 mission을 몰라서 초기화를 할 수가 없었습니다. 그래서 그 정보를 알고있는DetailIngCodebaseViewController에서 LetterViewController를 리턴하는 함수를 만들었습니다.

2. 과거에 왔던 알림을 눌러서 종료된 방의 쪽지함으로 이동했을 때 문제가 생겼습니다.

![image](https://user-images.githubusercontent.com/78677571/211331260-b009addb-a28e-4d98-9660-ee6e922e84b9.png)

위 사진 해당부분이 기본값으로 .PROCESSING으로 초기화 되고 있는데, 

![image](https://user-images.githubusercontent.com/78677571/211331535-3907ddcc-de02-4c47-b7f7-c513201eca0b.png)

viewDidLoad단계에서 해당 API 함수를 통해 값을 변경해주고 있습니다. 하지만 제가 만든 LetterViewController를 리턴하는 함수에서는 

<img width="887" alt="image" src="https://user-images.githubusercontent.com/78677571/211332345-b7088da6-80fa-4e56-a4f7-159968912497.png">
<img width="280" alt="image" src="https://user-images.githubusercontent.com/78677571/211332413-cfe6913d-1499-46e6-84be-0fd47ad9b9e9.png">

해당방은 이미 종료되어서 "POST"가 출력되어야 하는데 "PROCESSING"이 찍힙니다. 왜냐하면  
![image](https://user-images.githubusercontent.com/78677571/211332798-a746da7f-9c07-48f7-8b7d-f02c5a72b36c.png)
SceneDelegate에서 클래스로 바로 초기화만 하고 내부의 함수를 실행하기 때문에 viewDidLoad가 돌지 않습니다. 그래서 POST가 아닌 PROCESSING이 전달됩니다. 

### 그래서 어떤 문제가 발생하는데요??

아래 영상은 이미 마니또가 종료된 방에서 온 푸시알림을 뒤늦게 눌렀을때의 상황입니다.

https://user-images.githubusercontent.com/78677571/211333402-0994f8e0-8c16-489c-b532-62fa8cec9a53.MP4

위 영상에서 보시면 쪽지 쓰기가 가능합니다. 하지만 뒤로 나갔다 들어오면 이미 종료된 방이기 때문에 쪽지 쓰기가 불가능합니다.
이러한 문제가 있습니다... 😭

이 부분들을 어떤식으로 수정해야할지, 애초에 푸시알림을 눌러서 view를 이동하는 방식이 잘못된건지... 잘 모르겠네요.. ㅠ

---

### 다른 분들의 View들을 불가피하게 조금 손보게 되었는데, 그 부분은 슬랙으로 전달드렸습니다 !

<img width="1375" alt="image" src="https://user-images.githubusercontent.com/78677571/211334061-256658c9-a2bc-4152-aa95-3f5e0466457b.png">

## 📣 Related Issue

- close #357

## 📬 Reference

2023-01-09 14:49 UTC, MMMIIIN commented on Manito/Manito/Global/Supports/SceneDelegate.swift
> +    }
SceneDelegate에서 rootViewController를 바꾸는 코드입니다.
순서가 Main -> DetailIng -> Letter로 되는데
일반적으론 Main으로 이동한 후 거기서 DetailIng로 가는 코드를 실행하고, 또 DetailIng에서 Letter로 가는 코드를 실행하고 싶었는데, 어떻게 구현을 해야할지 감이 잘 안오더라구요...
NotificationCenter를 사용해야 하는건지... 그렇게 했을 때 메모리가 과연 누수가 생기진 않을까란 생각에 사용하지 않았습니다.

그래서 SceneDelegate에서 한번에 다 스택을 쌓아서 rootViewController를 바꿨습니다.

2023-01-09 14:51 UTC, MMMIIIN commented on Manito/Manito/Screens/Detail-Ing/DetailngCodebaseViewController.swift
> +    }
getLetterViewController로 작명할까 하다가 Swift에선 get으로 시작하는 네이밍을 잘 사용 안한다고 들어서 그냥 letterViewController로 작명했습니다.

해당 함수를 만든 이유는 SceneDelegate에서 LetterViewController를 접근하려고 했을 때 mission이 뭔지 알 수 없습니다.
그래서 DetailIng 부분에서 LetterViewController를 리턴하는 함수를 만들어서 SceneDelegate에서 사용중입니다.

2023-01-09 14:53 UTC, MMMIIIN commented on Manito/Manito/Screens/Letter/LetterViewController.swift
>      }
기존에는 쪽지함을 들어가는 방법이 하나뿐이었습니다. 진행중 방에 들어와서 쪽지함을 탭 하는 방법. 단 하나였습니다.
그래서 letterState는 당연히 디폴트인 내가 보낸 쪽지를 가리켰습니다.
하지만 마니또로부터 쪽지가 왔을때 푸시알림을 눌러서 쪽지함을 들어가는 방법이 생겼습니다.
PR 내용에 적어두었지만, 마니또에게 받은 메시지를 보려고 푸시 알림을 눌렀을텐데, 내가 보낸게 떠있는게 이상했기 때문에 그 부분을 수정하기 위해서 letterState란 변수로 상태를 컨트롤 하고자 했습니다.

2023-01-10 15:30 UTC, YoonAh-dev commented on Manito/Manito/Global/Supports/AppDelegate.swift
> +            sceneDelegate.changeRootViewWithMessageView(roomId: roomId)
p2;

현재 사용자가 푸시알림을 눌렀을 때 해당 payload에 roomId 값이 오지 않는 경우가 생길 수 있는데, 이에 대한 처리가 필요할 거 같습니다.

에러 처리가 프로젝트 전반적인 문제라서 각잡고 에러를 처리해야하긴 하지만 진행하면서 계속 신경쓰면서 진행하면 후에 각잡고 처리할 에러가 조금이라도 줄지 않을까 싶네요..👀

2023-01-10 15:32 UTC, YoonAh-dev commented on Manito/Manito/Global/Supports/SceneDelegate.swift
> +    func changeRootViewWithMessageView(roomId: Int) {
p5;

MessageView 라는게 LetterViewController를 뜻하는 걸까요?..👀

2023-01-10 15:35 UTC, YoonAh-dev commented on Manito/Manito/Global/Supports/SceneDelegate.swift
> +        rootViewController.pushViewController(letterViewController, animated: true)
p3;

설명해주신 순서가 `Main -> DetailIng -> Letter`긴 하지만 결론적으로 Letter 뷰가 바로 뜨는거잖아요? 영상도 그렇게 찍어주신 거 같구요. 그러면 굳이 animated를 true로 할 필요가 있을까요? false여도 상관없을 거 같은데, true로 하신 이유가 있으신가요?

2023-01-10 15:38 UTC, YoonAh-dev commented on Manito/Manito/Screens/Detail-Ing/DetailngCodebaseViewController.swift
> +        return letterViewController
p2;

이 부분이 상단에 있는 `letterBoxButton` 변수 선언 클로저 내부에 있는 action 코드와 비슷한 거 같습니다. 
함수로 뺀 뒤에 재사용할 수 있지 않을까 싶네요..

2023-01-10 15:48 UTC, YoonAh-dev commented
> 위 영상에서 보시면 쪽지 쓰기가 가능합니다. 하지만 뒤로 나갔다 들어오면 이미 종료된 방이기 때문에 쪽지 쓰기가 불가능합니다.
이러한 문제가 있습니다... 😭
이 부분들을 어떤식으로 수정해야할지, 애초에 푸시알림을 눌러서 view를 이동하는 방식이 잘못된건지... 잘 모르겠네요.. ㅠ

![스크린샷 2023-01-11 오전 12 42 53](https://user-images.githubusercontent.com/55099365/211596250-4ac16da0-5349-4778-8d98-4a5b926d9b01.png)

현재 Scenedelegate에서 바로 쪽지 뷰로 이동을 하도록 코드를 작성해주신 걸 확인했습니다. 제 생각에는 코드가 좀 더 재사용하기 좋은 모습이라면 SceneDelegate에서 root를 Main으로 잡는 코드만 짜고 Main -> Detail-ing -> Letter 코드는 각각의 VC에서 함수를 만들어서 이동하는게 좋지 않을까 싶습니다. 이미 다른 VC로 이동하는 코드가 각 VC마다 존재하기 때문에 해당 함수를 재사용하면 될 거라고 생각이 듭니다.

그랬을 때에 말씀해주신 종료된 방으로 나오는 문제도 해결이 될 거 같습니다. 어떠신가요?
물론 VC를 타고 타고 가는 방식이긴 하지만 이미 각 VC가 가지고 있는 함수가 있어서 해당 함수를 재사용한다면 큰 문제가 없을거라고 생각이 들었습니다. 

코드가 약간 달라져서 animated를 true했을 시에 뷰가 올라오는게 잘 보일 수는 있겠네요. 🤔

2023-01-10 15:50 UTC, YoonAh-dev commented on Manito/Manito/Screens/Detail-Ing/DetailngCodebaseViewController.swift
> +    }
함수 네이밍이 letterViewController가 되기 보다는 변수로 만드는 건 어떨까요?

```swift
lazy var letterViewController: UIViewController {
        guard let mission = missionContentsLabel.text else { return UIViewController() }
        let letterViewController = LetterViewController(roomState: roomType.rawValue,
                                                        roomId: roomId,
                                                        mission: mission,
                                                        letterState: .received)
        return letterViewController
}
```

2023-01-11 02:18 UTC, MMMIIIN commented on Manito/Manito/Screens/Detail-Ing/DetailngCodebaseViewController.swift
> +    }
그러네요 변수로 만들수도 있겠네요 ! 감사합니다 ^________^
[13bd539](https://github.com/DeveloperAcademy-POSTECH/MC2-Team5-Firefighter/pull/361/commits/13bd539c652cc46985972c0f64357855e9185feb)

2023-01-11 02:20 UTC, MMMIIIN commented on Manito/Manito/Global/Supports/AppDelegate.swift
> +            sceneDelegate.changeRootViewWithMessageView(roomId: roomId)
에러 처리라는게 어떻게 할 수 있을까요?? roomId값이 들어오지 않는다면 해당 뷰까지 이동 안하고 그냥 앱에 들어온 상태가 될 것 같은데... 추가적으로 처리해야할 부분이 있을까요?? alert을 띄우는 그런걸까요..??

2023-01-11 02:25 UTC, MMMIIIN commented on Manito/Manito/Global/Supports/SceneDelegate.swift
> +    func changeRootViewWithMessageView(roomId: Int) {
헉.. 그러네요 Letter로 이름을 바꿨습니다 !
`changeRootViewControllerWithLetterViewController`로 이름을 지을까하다가 너무 길어서 보기 불편할 것 같아서 controller 부분은 뺐습니다...

2023-01-11 02:29 UTC, MMMIIIN commented on Manito/Manito/Global/Supports/SceneDelegate.swift
> +        rootViewController.pushViewController(letterViewController, animated: true)
이 부분은 제가 일반적으로 느꼈던 경험을 토대로 반영을 했습니다. 알림이 와서 해당 알림을 눌러서 앱에 들어가게 되면, 목적지로 바로 가는게 아니라 이동하는게 눈에 보이더라구요 ! 그래서 animated를 true로 했습니다 !
하지만 제가 원하는대로 샥샥 이동하는게 보이진 않더라구요.. 이게 SceneDelegate 부분에서 코드를 다 실행해서 그런 것 같네요..

2023-01-11 02:46 UTC, MMMIIIN commented on Manito/Manito/Screens/Letter/LetterViewController.swift
> +    var letterState: LetterState {
그쵸그쵸 왜 그랬을까요...?? 하하

2023-01-11 12:21 UTC, creohwan commented on Manito/Manito/Global/Supports/SceneDelegate.swift
> +    }
> SceneDelegate에서 rootViewController를 바꾸는 코드입니다. 순서가 Main -> DetailIng -> Letter로 되는데 일반적으론 Main으로 이동한 후 거기서 DetailIng로 가는 코드를 실행하고, 또 DetailIng에서 Letter로 가는 코드를 실행하고 싶었는데, 어떻게 구현을 해야할지 감이 잘 안오더라구요... NotificationCenter를 사용해야 하는건지... 그렇게 했을 때 메모리가 과연 누수가 생기진 않을까란 생각에 사용하지 않았습니다.
> 
> 그래서 SceneDelegate에서 한번에 다 스택을 쌓아서 rootViewController를 바꿨습니다.

Q: AppDelegate 의 내에서, 혹은 AppDelegate의 userNotificationCenter 함수 내에서 이것들을 사용하면 안되는 이유가 있을까요..?? 똑같은 코드를 넣으면 되지 않을까??라는 생각이 문득 들어서 질문드려 봅니다 ㅎㅎ

2023-01-11 12:37 UTC, creohwan requested changes
고생하셨습니다!! 문득 생각이 든 것이 있어서 주절주절 적어봤습니다. 감사합니다 :)

2023-01-12 09:16 UTC, MMMIIIN commented on Manito/Manito/Global/Supports/SceneDelegate.swift
> +    }
물론 `AppDelegate`에서도 사용할 순 있지만, 결국 
`guard let sceneDelegate = UIApplication.shared.connectedScenes.first?.delegate as? SceneDelegate else { return }` 이렇게 `sceneDelegate`를 가져와서 사용합니다.
rootView를 변경하기 때문에 `SceneDelegate`에 `window`를 접근해야합니다 !
알림을 눌렀을때의 코드를 실행하기 위해 어쩔 수 없이 `AppDelegate`에서 코드가 시작되고, `SceneDelegate`의 코드에 접근하는 방식으로 사용중입니다 !

2023-01-12 12:37 UTC, creohwan commented on Manito/Manito/Global/Supports/SceneDelegate.swift
> +    }
> 물론 `AppDelegate`에서도 사용할 순 있지만, 결국 `guard let sceneDelegate = UIApplication.shared.connectedScenes.first?.delegate as? SceneDelegate else { return }` 이렇게 `sceneDelegate`를 가져와서 사용합니다. rootView를 변경하기 때문에 `SceneDelegate`에 `window`를 접근해야합니다 ! 알림을 눌렀을때의 코드를 실행하기 위해 어쩔 수 없이 `AppDelegate`에서 코드가 시작되고, `SceneDelegate`의 코드에 접근하는 방식으로 사용중입니다 !

아하 그렇군요! 감사합니다 =D

2023-01-12 14:25 UTC, MMMIIIN commented on Manito/Manito/Global/Supports/AppDelegate.swift
> +
그러네요 알림의 유형에 따라 어떤 함수가 실행되어야 하는지 구분해야겠네요 !
디너의 말씀대로 `response.notification.request.identifier`이 값을 찍어봤는데 
<img width="506" alt="스크린샷 2023-01-12 오후 11 13 07" src="https://user-images.githubusercontent.com/78677571/212091333-e6f25cd2-e517-4169-943e-25bf921dc115.png">

<img width="502" alt="스크린샷 2023-01-12 오후 11 14 33" src="https://user-images.githubusercontent.com/78677571/212091354-6b222e23-b526-40e7-8510-e86e96355186.png">

각각 다르게 나오더라구요 ! 진짜 고유값이라 매번 다른 것 같은데, 이 부분은 서버 선생님들과 얘기해서 payload에 값을 추가하는 방식으로 컨트롤 해야할 것 같네요 !

> 또한 앱 사용 중 알림을 눌렀는지, 아닌 상태인지도 판별할 수 있다고 하네요! 만약 B방에서 구경하다가, A방 알림이 떴을 때 그 알림을 누른 상황이라면, 그때 back을 하면 어떤 방이 나와야 자연스러울까요?? A방일까요? 아니면 B방일까요? 궁금증이 생겼습니다.

이 상황에 대해서는 앱 사용중에 눌렀을 때의 코드도 따로 만들어야 할 것 같네요 ! 현재는 루트뷰를 바꾸는 코드로 실행되는데, 앱 사용중이라면 해당 방의 쪽지함 뷰만 navigation 스택에 추가하면 될 것 같네요 !

이러한 작업들은 다른 기능이 추가된다면 그때 진행하는게 맞는 것 같습니다 ! 앱 사용중에 다른 알림을 누른다고 해서 크게 문제가 되는 상황도 아니구요 !

2023-01-12 14:35 UTC, MMMIIIN commented
> > 위 영상에서 보시면 쪽지 쓰기가 가능합니다. 하지만 뒤로 나갔다 들어오면 이미 종료된 방이기 때문에 쪽지 쓰기가 불가능합니다.
> > 이러한 문제가 있습니다... 😭
> > 이 부분들을 어떤식으로 수정해야할지, 애초에 푸시알림을 눌러서 view를 이동하는 방식이 잘못된건지... 잘 모르겠네요.. ㅠ
> 
> ![스크린샷 2023-01-11 오전 12 42 53](https://user-images.githubusercontent.com/55099365/211596250-4ac16da0-5349-4778-8d98-4a5b926d9b01.png)
> 
> 현재 Scenedelegate에서 바로 쪽지 뷰로 이동을 하도록 코드를 작성해주신 걸 확인했습니다. 제 생각에는 코드가 좀 더 재사용하기 좋은 모습이라면 SceneDelegate에서 root를 Main으로 잡는 코드만 짜고 Main -> Detail-ing -> Letter 코드는 각각의 VC에서 함수를 만들어서 이동하는게 좋지 않을까 싶습니다. 이미 다른 VC로 이동하는 코드가 각 VC마다 존재하기 때문에 해당 함수를 재사용하면 될 거라고 생각이 듭니다.
> 
> 그랬을 때에 말씀해주신 종료된 방으로 나오는 문제도 해결이 될 거 같습니다. 어떠신가요? 물론 VC를 타고 타고 가는 방식이긴 하지만 이미 각 VC가 가지고 있는 함수가 있어서 해당 함수를 재사용한다면 큰 문제가 없을거라고 생각이 들었습니다.
> 
> 코드가 약간 달라져서 animated를 true했을 시에 뷰가 올라오는게 잘 보일 수는 있겠네요. 🤔

https://user-images.githubusercontent.com/78677571/212092758-0dd3db12-57f3-42f6-bdc9-39735c4d6eef.MP4


강제로 0.5초 딜레이를 둬서 애니메이션 이동이 보이게끔 구현했습니다 !
각각의 뷰컨에 이동하는 함수를 만들었는데, 막상 사용되는 곳이 조금 애매하네요..
SceneDelegate에서 mainViewController의 함수를 실행시키고, MainViewController에서 DetailIng 쪽 코드를 실행시키고... 이게 맞는 방법인지는 잘 모르겠네요..

[3948e3f](https://github.com/DeveloperAcademy-POSTECH/MC2-Team5-Firefighter/pull/361/commits/3948e3f9cd9d7c4eb7d49b81556ff44a4aaaef4e)

2023-01-16 03:12 UTC, YoonAh-dev commented on Manito/Manito/Global/Supports/SceneDelegate.swift
> +    }
@MMMIIIN @creohwan 

첨언을 해보자면,
iOS 13 이후부터는 AppDelegate가 혼자서 하던 역할을 AppDelegate와 SceneDelegate가 나눠서 진행하게 되었습니다.
AppDelegate는 Process의 라이프 사이클을 관리하고, SceneDelegate가 AppDelegate가 하던 UI 상태 변화를 application에 알리는 역할을 하게 됩니다.

위의 함수를 SceneDelegate에 넣어줘야 하는 이유는 AppDelegate에서도 사용할 수 있지만 해당 코드가 Process 관련된 함수라기 보다는 UI의 상태 변화와 관련된 코드이기 때문입니다. 그런 이유에서 SceneDelegate에 넣어두는 게 맞지 않나 생각이 듭니다.

2023-01-16 03:15 UTC, YoonAh-dev commented on Manito/Manito/Global/Supports/AppDelegate.swift
> +            sceneDelegate.changeRootViewWithMessageView(roomId: roomId)
앱에 들어왔을 때 문제가 생겼다는 alert를 띄워야 하지 않을까요? 앱이 켜지기 전에 에러 처리는 안될 거 같고, 할 수 있는건 들어왔을 때 alert 띄우는게 최선일 것 같습니다.

2023-01-16 03:25 UTC, YoonAh-dev commented on Manito/Manito/Global/Supports/SceneDelegate.swift
> +        rootViewController.pushViewController(letterViewController, animated: true)
이미 push를 다해서 stack에 쌓은 상태에서 rootViewController를 설정해줬기 때문인거 같네요.
stack에는 이미 VC가 다 쌓여있기 때문에 가장 위에 있는 VC가 최초로 보이는 거 같습니다.

2023-01-16 03:43 UTC, YoonAh-dev commented
@MMMIIIN 

> 강제로 0.5초 딜레이를 둬서 애니메이션 이동이 보이게끔 구현했습니다 !
각각의 뷰컨에 이동하는 함수를 만들었는데, 막상 사용되는 곳이 조금 애매하네요..
SceneDelegate에서 mainViewController의 함수를 실행시키고, MainViewController에서 DetailIng 쪽 코드를 실행시키고... 이게 맞는 방법인지는 잘 모르겠네요..

음.. 써주신 코드보고 어떤 상황인지는 이해가 되었습니다. 일단, 화면을 push되는 코드가 계속 중복된다고 생각이 들어서 각 VC마다 push하는 함수를 하나로 만드는게 제일 우선일 것 같고, 해당 함수를 internal로 만들게 된다면 SceneDelegate에서도 가져와서 사용할 수 있지 않을까 싶습니다..

2023-01-16 03:50 UTC, YoonAh-dev commented on Manito/Manito/Global/Supports/AppDelegate.swift
> +
@MMMIIIN @creohwan 

푸시알림의 유형은 `response.notification.request.content.threadIdentifier`로 나눠서 받는 걸로 압니다.
서버 쪽에서 threadIdentifier로 다른 값을 주고 해당 값을 받은 클라쪽에서 해당 identifier를 통해서 구분짓는걸로 압니다.

앱 사용 중인지 아닌지는 `UIApplication.shared.applicationState`로 판별가능합니다.

2023-01-16 06:07 UTC, MMMIIIN commented on Manito/Manito/Global/Supports/AppDelegate.swift
> +            sceneDelegate.changeRootViewWithMessageView(roomId: roomId)
결국 AppDelegate 단에서 Alert를 표시하려면 UIViewController가 필요한데, MainViewController에 Alert를 표시하는 함수를 만들어서 실행시키면 될까요 ??
그리고 AppDelegate에서 if let 쪽 코드의 else 부분에 추가하는 방식이 맞을까요 ??

2023-01-16 06:18 UTC, MMMIIIN commented on Manito/Manito/Global/Supports/AppDelegate.swift
> +            sceneDelegate.changeRootViewWithMessageView(roomId: roomId)
[40591ab](https://github.com/DeveloperAcademy-POSTECH/MC2-Team5-Firefighter/pull/361/commits/40591ab081ad06a0868fa00e2289adf2d5e69e17)

이렇게 만들어뒀는데 괜찮을까요 ??

2023-01-16 06:32 UTC, MMMIIIN commented
> 
> 음.. 써주신 코드보고 어떤 상황인지는 이해가 되었습니다. 일단, 화면을 push되는 코드가 계속 중복된다고 생각이 들어서 각 VC마다 push하는 함수를 하나로 만드는게 제일 우선일 것 같고, 해당 함수를 internal로 만들게 된다면 SceneDelegate에서도 가져와서 사용할 수 있지 않을까 싶습니다..

@YoonAh-dev 
리뷰 감사합니다 ! 단지 어떤 부분을 말씀하시는지 이해가 안가는 부분이 있어서 질문드립니다 !

push 되는 코드가 중복이 된다는게 어떤 말씀일까요 ??
MainViewController에서 
```swift
    private func pushDetailView(status: RoomStatus, roomIndex: Int, index: Int? = nil) {
        switch status {
        case .waiting:
            guard let index = index else { return }
            let viewController = DetailWaitViewController(index: index)
            viewController.roomInformation = rooms?[roomIndex]
            self.navigationController?.pushViewController(viewController, animated: true)
        default:
            guard let roomId = rooms?[roomIndex].id?.description
            else { return }
            let viewController = DetailingCodebaseViewController(roomId: roomId)
            self.navigationController?.pushViewController(viewController, animated: true)
        }
    }
    
    func pushDetailViewController(roomId: Int) {
        let viewController = DetailingCodebaseViewController(roomId: roomId.description)
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.5) {
            self.navigationController?.pushViewController(viewController, animated: true)
            viewController.pushLetterViewControllerReceivedType()
        }
    }
```

1. 위의 두 함수 코드가 중복된다는 말씀일까요 ??
아니면 DetailIngCodebaseViewController에서
```swift
self?.navigationController?.pushViewController(viewController, animated: true)
```
2. 이렇게 UIAction에 추가되는 코드가 중복된다는 의미일까요 ??

위의 첫 번째 문제는 초기화 단계에서 전달해야하는 정보가 있는게 문제라 생각해서, 개선이 필요해 보입니다.
두 번째 문제는 몇몇 뷰들은 StoryBoard로 만들어져 있어서 
```swift
@objc
    private func pushFriendListViewController(_ gesture: UITapGestureRecognizer) {
        let storyboard = UIStoryboard(name: "DetailIng", bundle: nil)
        guard let viewController = storyboard.instantiateViewController(withIdentifier: FriendListViewController.className) as? FriendListViewController else { return }
        guard let roomId = Int(roomId) else { return }
        viewController.roomIndex = roomId
        self.navigationController?.pushViewController(viewController, animated: true)
    }
```
기존 코드로 만들어진 방법과는 추가적으로 스토리보드의 이름이 필요해서 두가지 push를 혼용하는 함수로 만들기 애매하다 생각했고, property에 들어가는 push 들은 하나의 함수로 만들 수 있겠지만, 
```swift
let letterViewController = LetterViewController(roomState: roomType.rawValue,
                                                            roomId: roomId,
                                                            mission: mission,
                                                            letterState: .sent)
            self?.navigationController?.pushViewController(letterViewController, animated: true)
```

여기도 첫 번째 이유와 같이 초기화 과정에 필요한 정보들이 있어서 전체적인 수정이 필요해 보입니다. 

**그래서 하나의 함수로 만드는게 조금 애매하다 생각합니다.**


다음뷰를 그리기 위해서 현재뷰에서 넘겨줘야하는 정보들이 있는 부분이 여러모로 불편한 것 같습니다. API통신을 통해 받아올 수 있는 정보들인데 앞에서 넘겨줘야 하는게 뷰들간의 의존성이 생기는 듯한 느낌이라 수정하면 어떨까 싶습니다...

혹시 제가 리뷰를 잘못 이해했다면 어떤 부분을 말씀하시는지 구체적으로 알려주시면 감사하겠습니다 !

2023-01-16 14:41 UTC, YoonAh-dev commented on Manito/Manito/Global/Supports/AppDelegate.swift
> +            sceneDelegate.changeRootViewWithMessageView(roomId: roomId)
어.. MainViewController에서 방 id가 없을 때 띄워주어야 한다고 생각이 드는데 당장 문제가 없다면 이대로 진행하고 나중에 수정을 하는 것이 어떨까 싶습니다.

하단 코멘트에서 하나의 함수로 만드는데 어려움이 있다고 해주셨기도 하고, 해당 브랜치에서 개선을 하기엔 큰 작업이 될 거 같아서 다른 브랜치에서 진행하는 게 좋을 거 같네요. 추후에는 꼭 수정해야할 부분인 거 같습니다.

2023-01-16 14:47 UTC, YoonAh-dev approved these changes
현재 푸시알림을 진행하는 로직에 대해서는 큰 문제가 없어보여서 어푸르브를 드립니다.
하지만 쪽지뷰로 이동하는 흐름에 있어서 아직까지 의문인 부분 + 개선해야할 부분이 많아 보입니다.
(케미 코드에서 문제가 있다가보단 전체적인 프로젝트에 있어서 문제라는 뜻입니다.)

해당 부분은 당장 해당 브랜치가 아니라 다른 브랜치를 파서 대대적으로 진행해야할 문제라고 인식이 되어서 회의때 논의를 한 후에 플로우 로직을 개선을 해보는 식으로 진행하면 좋을 것 같습니다.

수고하셨습니다!

2023-01-16 14:59 UTC, creohwan approved these changes
푸쉬 알림 생각보다 만만하지 않은 친구였군요!! 고생하셨습니다 =D

2023-01-16 15:06 UTC, merged