[CHORE] Splash, LoginViewController 컨벤션을 적용했습니다 !
DeveloperAcademy-POSTECH/MC2-Team5-Firefighter pull request #385
Opened 2023-02-21 07:16 UTC by MMMIIIN

## 🌁 Background

SplashViewController와 LoginViewController 부분의 코드 컨벤션을 적용했습니다

## 👩‍💻 Contents

- 주석 위치와 이름 변경
- setup 함수 분리
- self키워드 명시
- 불필요한 completion 코드 삭제
- 타입 명시

## ✅ Testing

`feature/384-login-splash-convention` 브랜치로 오셔서 코드를 확인해 주세요 !

## 📱 Screenshot

<img width="235" alt="image" src="https://user-images.githubusercontent.com/78677571/220274265-58ba02d8-e57c-4a5d-b1fd-fdf85288d234.png">
여기 부분 작업했습니다

## 📝 Review Note

deinit 부분의 주석이 init으로 되어야 할지, life cycle로 되어야 할지가 조금 애매해서 init으로 뒀습니다. 혹시 수정이 필요하다면 말씀해주세요 !

## 📣 Related Issue

- close #384

## 📬 Reference

2023-02-22 02:13 UTC, YoonAh-dev commented on Manito/Manito/Screens/Login/LoginViewController.swift
>                                  let viewController = storyboard.instantiateViewController(withIdentifier: "MainNavigationController")
p1;

95 라인에 있는 주석은 지워도 괜찮지 않을까요? 꼭 필요한 주석인가요?

2023-02-22 02:14 UTC, YoonAh-dev commented on Manito/Manito/Screens/Login/LoginViewController.swift
>                                  let viewController = storyboard.instantiateViewController(withIdentifier: "MainNavigationController")
++) 121, 124번 라인에 있는 주석도 사용하지 않으면 지워도 되지 않을까요. revoked, notFound case가 break가 나온다면 default로 합치는것도 방법일 것 같습니다. 후에 revoked, notFound에 대한 에러 처리를 추가로 하면 좋을 것 같네요.

2023-02-22 02:15 UTC, YoonAh-dev commented on Manito/Manito/Screens/Login/LoginViewController.swift
>                                  let viewController = storyboard.instantiateViewController(withIdentifier: "MainNavigationController")
++) 146번 라인에 있는 didCompleteWithError에 대한 부분도 에러 처리를 꼼꼼히 하면 좋지 않을까 싶습니다. 해당 브랜치는 컨벤션 관련 브랜치니깐 후에 다른 브랜치에서 추가적으로 해주시면 좋을 것 같아요.

2023-02-22 02:18 UTC, YoonAh-dev commented on Manito/Manito/Screens/Login/LoginViewController.swift
>      override func setupLayout() {
p1;

viewDidLoad는 life cycle 영역에 들어가야 하고, setupLayout은 override 영역에 들어가야 맞는 거 같네요.

2023-02-22 02:20 UTC, YoonAh-dev commented on Manito/Manito/Screens/Splash/SplashViewController.swift
> +    // MARK: - override
p1;

life cycle이 맞는 표기일 거 같아요.
![스크린샷 2023-02-22 오전 11 19 56](https://user-images.githubusercontent.com/55099365/220504251-fcf68659-246f-41b4-a2f3-339bb7510442.png)

2023-02-22 02:22 UTC, YoonAh-dev commented on Manito/Manito/Screens/Splash/SplashViewController.swift
>          DispatchQueue.main.asyncAfter(deadline: .now() + 1.5) {
p4;

DispatchQueue 관한 부분을 함수로 분리하면 좋을 거 같습니다.
따로 컨벤션으로 정하진 않았지만 저희끼리 암묵적으로 life cycle 함수들 내부는 메소드들로 구성하기로 했던 거 같아서요!

2023-02-22 02:24 UTC, YoonAh-dev commented on Manito/Manito/Screens/Splash/SplashViewController.swift
>              let isSetFcmToken = UserDefaultStorage.isSetFcmToken
p5;

이 isSetFcmToken에 대한 궁금한 점이 두 가지 있습니다 :
1. 다른 UserDefault Value와는 다르게 viewDidLoad에서 선언을 한 이유가 있는지
2. isLogin를 true라는건 이미 로그인을 한 상태인건데, isSetFcmToken으로도 로그인을 했는지를 확인하는 이유가 있는지

2번 같은 경우에는 FcmToken를 설정안한(그 전에 로그인한) 유저때문인거 같긴한데 맞나요?

2023-02-22 02:30 UTC, YoonAh-dev requested changes
p1 관련 코멘트들만 해결이 되면 어푸르브하겠습니다! 👍🏻

2023-02-28 03:47 UTC, coby5502 commented on Manito/Manito/Screens/Splash/SplashViewController.swift
>              let isSetFcmToken = UserDefaultStorage.isSetFcmToken
2번 같은 경우에, 신선생님 말씀대로, 그 이유 때문이라고 케미가 얘기했던거같아요~

2023-03-04 13:57 UTC, coby5502 requested changes
듀나님꺼 수정되면 어푸르브할게요.

2023-03-14 07:54 UTC, MMMIIIN commented on Manito/Manito/Screens/Login/LoginViewController.swift
>                                  let viewController = storyboard.instantiateViewController(withIdentifier: "MainNavigationController")
공식문서에서 긁어오다보니 남은 잔해 같네요!
삭제했습니당
[adc01f4](https://github.com/DeveloperAcademy-POSTECH/MC2-Team5-Firefighter/pull/385/commits/adc01f43dccf071a63e4fae0b5fd5736a03eb997)

2023-03-14 07:55 UTC, MMMIIIN commented on Manito/Manito/Screens/Login/LoginViewController.swift
> +        return self.view.window!
맞는진 모르겠지만 `guard let`으로 빼봤습니다
확인 부탁드려요!
[c331867](https://github.com/DeveloperAcademy-POSTECH/MC2-Team5-Firefighter/pull/385/commits/c3318672a61898c8c11ba67fac93d3a38d9c465c)

2023-03-14 07:55 UTC, MMMIIIN commented on Manito/Manito/Screens/Login/LoginViewController.swift
>      override func setupLayout() {
그러네요! 감사합니다!
[9b80595](https://github.com/DeveloperAcademy-POSTECH/MC2-Team5-Firefighter/pull/385/commits/9b805959a3d1ad0005ddbc44b7eb1843285817a1)

2023-03-14 07:55 UTC, MMMIIIN commented on Manito/Manito/Screens/Splash/SplashViewController.swift
> +    // MARK: - override
좋습니다!
수정완료!
[12b53a7](https://github.com/DeveloperAcademy-POSTECH/MC2-Team5-Firefighter/pull/385/commits/12b53a7a8edda524c02882b96f477696301edf01)

2023-03-14 07:56 UTC, MMMIIIN commented on Manito/Manito/Screens/Splash/SplashViewController.swift
>          DispatchQueue.main.asyncAfter(deadline: .now() + 1.5) {
넵! 함수명은 조금 고민하다 지어봤는데 어떤지 확인 부탁드립니다!
[0731642](https://github.com/DeveloperAcademy-POSTECH/MC2-Team5-Firefighter/pull/385/commits/07316424b174a167030662cefe3c390bf244ee02)

2023-03-14 07:58 UTC, MMMIIIN commented on Manito/Manito/Screens/Splash/SplashViewController.swift
>              let isSetFcmToken = UserDefaultStorage.isSetFcmToken
1번은 예전에 제가 왜 그랬는지 모르겠군요... 하하
위쪽으로 빼두었습니다 !
[d26f6bc](https://github.com/DeveloperAcademy-POSTECH/MC2-Team5-Firefighter/pull/385/commits/d26f6bc73fba099c8085f00d09d2cbcfefaedc55)

2번은 푸시알림을 처음 도입했을때 로그인하는 과정에서 FCM Token값을 서버로 넘겨줘야하기 때문에 다시 로그인 시킬 필요가 있었습니다! 그래서 작성한 코드입니다!

2023-03-14 10:06 UTC, YoonAh-dev approved these changes
고생하셨습니다!

2023-03-14 13:42 UTC, dangsal approved these changes
잘 보았습니다! 저도 잘 해보겠습니다!

2023-03-16 01:34 UTC, coby5502 approved these changes

2023-03-16 12:22 UTC, merged