[CHORE] DetailViewController 를 삭제하고 Codebase 뷰컨트롤러를 변경했습니다.
DeveloperAcademy-POSTECH/MC2-Team5-Firefighter pull request #405
Opened 2023-03-13 12:40 UTC by dangsal

## 🌁 Background

현재 디너가 스토리 보드의 코드 (DetailViewController) 에서 (DetailCodebaseViewController) 로 전환하는 과정이 있었고, 그 이후 DetailViewController 파일이 삭제되지 않고 남아있었습니다. 
그래서 그 DetailViewController 파일을 지우고 DetailCodebaseViewController 를 DetailViewController 로 클래스 이름 변경하는 작업을 진행했습니다.

## 👩‍💻 Contents

- 기존 스토리 보드에 연결되어있던 DetailViewController 파일 삭제
- 기존 DetailViewController 스토리보드 삭제
- DetailCodebaseViewController 에서 DetailViewController 로 네이밍 변경

## ✅ Testing

feature/404-deleteView 로 오셔서 실행 후 진행 중인 방 들어와 보시면 됩니다! 잘 작동 합니다..!! 하하 

## 📱 Screenshot

https://user-images.githubusercontent.com/59243274/224702613-c1245b64-68a3-42ac-b6cc-684ab4ccced2.mp4

## 📝 Review Note

삭제하고 실행 했을 때..는 문제 없습니다..!! 
하하 
문제없을거에요...

## 📣 Related Issue

- close #404 

## 📬 Reference

2023-03-14 02:42 UTC, YoonAh-dev reviewed
호야! 클래스 이름은 바뀌었는데, 파일 이름은 그대로 DetailingCodebaseViewController인 거 같아서요. 파일명도 바꿔주실 수 있나요?

2023-03-14 02:47 UTC, YoonAh-dev reviewed
디테일-ing 뷰에서 함께 하는 친구들 뷰로 이동할때 앱이 터집니다! 확인부탁드려요
![스크린샷 2023-03-14 오전 11 46 31](https://user-images.githubusercontent.com/55099365/224879899-e3069916-9c4f-40a5-8f20-f0c092262c71.png)

2023-03-14 09:56 UTC, MMMIIIN requested changes
혹시 푸시알림으로 앱에 들어갔을때 문제가 있나 싶어서 테스트 해봤는데 문제없네요!
듀나가 말씀해주신대로 함께하는 친구들쪽으로 가면 앱이 박살나네요!
확인 부탁드립니다 ^_________^

2023-03-14 12:42 UTC, dangsal commented
확인 결과 
<img width="1266" alt="스크린샷 2023-03-14 오후 9 32 57" src="https://user-images.githubusercontent.com/59243274/225002040-2068b98a-41da-4dd0-b877-058dbe534b6a.png">

함께하는 친구들 또한 스토리보드로 지금 구현이 되어있습니다..! 제가 Detail 스토리보드 또한 필요없겠다 싶어서 지웠는데 그게 문제였어요!

앞으로 할 일로 함께하는 친구들 또한 코드베이스로 전환하는 과정이 필요해 보입니다! 현재는 일단 DetailView 관련 한 파일만 지웠습니다! 
그리고 듀나가 말씀하신 파일명 변경도 진행했습니다!

2023-03-14 13:59 UTC, YoonAh-dev commented on Manito/Manito/Screens/Detail-Ing/DetailngViewController.swift
> +final class DetailingViewController: BaseViewController {
p1;

파일명이 Detailing가 아니고 Detailng으로 되어있는거 같아요!

2023-03-14 14:08 UTC, YoonAh-dev reviewed
@dangsal 빌드 잘 됩니다! p1 코멘트만 해결해주시면 어푸르브할게요!

2023-03-14 14:27 UTC, dangsal commented on Manito/Manito/Screens/Detail-Ing/DetailngViewController.swift
> +final class DetailingViewController: BaseViewController {
안경을 사야하나
라식을 해야하나
손가락을 새로 장착해야하나... 하....

2023-03-15 05:23 UTC, YoonAh-dev approved these changes
고생하셨습니다!! 👍🏻

2023-03-20 11:20 UTC, coby5502 approved these changes

2023-03-21 00:47 UTC, MMMIIIN reviewed
마지막 컨플릭트만 해결 부탁드립니당 ~~

2023-03-21 12:04 UTC, dangsal commented
컨플릭트 해결 했는데 혹시 확인한번씩만 부탁드려요..!

2023-03-21 12:32 UTC, YoonAh-dev commented
@dangsal 잘 됩니다~!

2023-03-21 12:33 UTC, MMMIIIN approved these changes
감사합니다~~~
수고 많으셨어요 ^_________^

2023-03-21 13:26 UTC, merged