[REFACTOR] DetailWaitController의 View를 분리했습니다.
DeveloperAcademy-POSTECH/MC2-Team5-Firefighter pull request #444
Opened 2023-04-18 15:25 UTC by MMMIIIN

## 🌁 Background

제 작고 귀여운 DetailWaitViewController의 View분리를 진행했습니다.
듀나와 호야가 미리 View 분리 PR을 올려주셔서 수월하게 작업했습니다.

## 👩‍💻 Contents

### DetailWaitView 분리 후 ViewController간의 역할 위임

<img width="1201" alt="image" src="https://user-images.githubusercontent.com/78677571/232821834-63da3b3f-f1fc-4266-bf56-99bf0b1435ab.png">

ViewController에선 View의 Configure 함수를 실행하고, 
View에선 ViewController로 각각의 액션들을 Delegate합니다.
(ViewController가 View를 담고있어서 그렇게 그려봤더니 더 이해하기 불편할까요...)

처음 View를 분리하다보니 어색한 부분이 있을 수 있습니다... 잘 부탁드립니다.. ^_________^

1. ToastView의 showToast의 방식이 기존에는 UIViewController를 넘겨 받아서 띄워주는 방식이었는데, UIView에 띄우는 함수를 하나 더 만들었습니다. 기존의 UIViewController에 띄우는 코드도 UIView로 합칠 수 있습니다. 이 부분은 얘기해보고 하나로 합치면 좋을 것 같습니다.

## ✅ Testing

`feature/441-refactor-detailwait` 브랜치로 오셔서 돌려보시면 됩니다.

## 📱 Screenshot

https://user-images.githubusercontent.com/78677571/232824702-23e73fdd-19d1-4fd3-9e34-87c455309ba3.mp4

## 📝 Review Note

1. View의 각각의 내용들을 전달하기 위해 `configureLayout`란 함수에서 room을 매개변수로 전달 받아서 각각을 적용하는데 더 괜찮은 방법이 있는지 궁금합니다.
3. Delegate의 `presentRoomEditViewController`, `presentEditViewControllerAfterShowAlert` 두 함수가 있는데 이름에서 알 수 있다 시피 결국 `EditViewController`를 `present`하는 함수인데 하나는 바로 띄우지만, 하나는 Alert이후에 띄웁니다. Delegate는 각각 나누어져 있지만 ViewController의 내부에선 `presentDetailEditViewController`의 함수를 공통으로 사용하긴 합니다만... 조금 찝찝한 상태입니다..

### 현재 방 정보 수정은 가능하지만 View에 바로 적용되지 않습니다.
기존에도 DetailWait과 DetailEdit이 엮여있었는데, 현재는 DetailWait만 분리해서 아직은 매끄럽게 되어있지 않습니다. 감안하고 봐주세요!

## 📣 Related Issue

- close #441

## 📬 Reference

https://github.com/DeveloperAcademy-POSTECH/MC2-Team5-Firefighter/pull/413
https://github.com/DeveloperAcademy-POSTECH/MC2-Team5-Firefighter/pull/423

2023-04-21 16:16 UTC, YoonAh-dev requested changes
`DetailWaitView`를 더 자세히 보고 싶은데 집중력이 바닥이 나서 오늘은 여기까지 하겠습니다!
일단 View 부분은 추가적으로 생각나는거나 보이는게 있으면 내용을 더 적어두겠습니다. 

> View의 각각의 내용들을 전달하기 위해 configureLayout란 함수에서 room을 매개변수로 전달 받아서 각각을 적용하는데 더 괜찮은 방법이 있는지 궁금합니다.

이건 View 좀 더 보면서 생각해보겠습니다. 지금 상태로는 configuration를 쪼개면 좋을 거 같아요. 뷰 컴포넌트 내용 구성하는 부분들이 모여있으니깐 한 눈에 보이지 않는거 같습니다.

> Delegate의 presentRoomEditViewController, presentEditViewControllerAfterShowAlert 두 함수가 있는데 이름에서 알 수 있다 시피 결국 EditViewController를 present하는 함수인데 하나는 바로 띄우지만, 하나는 Alert이후에 띄웁니다. Delegate는 각각 나누어져 있지만 ViewController의 내부에선 presentDetailEditViewController의 함수를 공통으로 사용하긴 합니다만... 조금 찝찝한 상태입니다..

음 현재처럼 나누는게 제일 최선이지 않을까요? Alert를 띄우는가 안띄우는가를 분기처리하는것도 코드가 별로 일 거 같습니다. delegate 메소드 네이밍을 수정하면 행동에 대한 부분이 안보여서 좀 덜 찝찝하지 않을까요.....?

2023-04-21 16:16 UTC, YoonAh-dev commented on Manito/Manito/Screens/Detail-Wait/DetailWaitViewController.swift
> +    // FIXME: - 나가기 테스트 해야함
q;

나가기 테스트는 아직 완료되진 않은건가요?

2023-04-21 16:16 UTC, YoonAh-dev commented on Manito/Manito/Screens/Detail-Wait/View/DetailWaitView.swift
> +    private let imgNiView: UIImageView = {
p1;

뭐라고 써야 좋을지는 모르겠지만 네이밍 수정이 필요할 거 같습니다! 
![스크린샷 2023-04-22 오전 1 06 40](https://user-images.githubusercontent.com/55099365/233683429-76f83f37-df19-4ba3-8e95-1b43974ad5fb.png)

2023-04-21 16:16 UTC, YoonAh-dev commented on Manito/Manito/Screens/Detail-Wait/View/DetailWaitView.swift
> +    private func showStartButtonForAdmin(_ isOwner: Bool) {
p3;

전체적으로 Admin과 Owner 라는 단어를 혼용하고 있어서 하나로 통일해주시면 좋을 것 같습니다.

2023-04-21 16:16 UTC, YoonAh-dev commented on Manito/Manito/Screens/Detail-Wait/View/DetailWaitView.swift
> +    func showAlert(title: String, message: String)
p3;

저번 회의에 Delegate 메소드처럼 네이밍을 하는걸로 했던거 같아서요!
현재 네이밍은 결론적으로 View에서 일어나는 액션으로 네이밍이 되어있어서 수정을 해보면 좋을 것 같은데 어떠신가요,,?

2023-04-22 04:47 UTC, MMMIIIN commented on Manito/Manito/Global/Extension/Date+Extension.swift
> +    }
넵 그렇겠군요!

2023-04-22 04:47 UTC, MMMIIIN commented on Manito/Manito/Global/Literal/TextLiteral.swift
> +    static let detailWaitViewControllerLoadDataTitle: String = "오류 발생"
넵 DetailWait쪽 뿐만 아니라 전체적으로 Error Alert에 사용할 TextLiteral을 만들었습니다

2023-04-22 04:57 UTC, MMMIIIN commented on Manito/Manito/Global/UIComponent/ToastPopupView.swift
> +    }
넵 그러네요.. 뷰를 처음 분리하다보니 토스트를 뷰 쪽에서 띄워야한다고 생각했나봐요... 다 분리하고 보니까 delegate로 넘겨서 ViewController에게 역할을 주는 게 맞는 것 같네요!

2023-04-22 05:14 UTC, MMMIIIN commented on Manito/Manito/Screens/Detail-Wait/DetailWaitViewController.swift
> +            viewController.endDateText = endDate
오호! 좋은 의견이네요 감사합니다 ^_________^
이 다음 PR인 DetailEditViewController의 View를 분리하는 PR에서 이 부분의 코드를 조금 더 줄였는데, 여기서 반영한 것과 합쳐지면 매우 간단해 지겠네요
오예~ 감사합니다

2023-04-22 05:15 UTC, MMMIIIN commented on Manito/Manito/Screens/Detail-Wait/DetailWaitViewController.swift
> +    // FIXME: - 나가기 테스트 해야함
네네 누군가 방을 만들어주셔야 테스트 가능합니다... 하하

2023-04-22 05:18 UTC, MMMIIIN commented on Manito/Manito/Screens/Detail-Wait/View/DetailWaitView.swift
> +    private let imgNiView: UIImageView = {
네넵 그렇네요
캐릭터 이미지가 "Ni"라서 네이밍이 조금 애매해서 Character란 네이밍을 추가했습니다.

2023-04-22 05:22 UTC, MMMIIIN commented on Manito/Manito/Screens/Detail-Wait/View/DetailWaitView.swift
> +    private func showStartButtonForAdmin(_ isOwner: Bool) {
네네! isAdmin으로 통일했습니다 ^________^

2023-04-22 05:24 UTC, MMMIIIN commented on Manito/Manito/Screens/Detail-Wait/View/DetailWaitView.swift
> +    func showAlert(title: String, message: String)
저도 네이밍 질문 드리고 싶었는데, Delegate 메소드처럼 네이밍 한다는게 어떻게 지어야 하는지 헷갈리더라구요...
startManitto -> didTapStartButton 이런 식으로 고치면 될까요??

2023-04-22 08:52 UTC, YoonAh-dev commented on Manito/Manito/Global/UIComponent/ToastPopupView.swift
> +    }
저도 뷰에서 띄울지, VC에서 띄울 지 고민했을 거 같아요.
어차피 ViewController가 View를 소유하고 있는 입장이니깐 Toast 정도는 VC에서 해줘도 괜찮지 않을지...
후에 다른 아키텍쳐로 넘어가도 VC는 결국 View의 역할을 할거라서 장기적인 측면에서도 괜찮을 거 같습니다!

2023-04-22 08:57 UTC, YoonAh-dev commented on Manito/Manito/Screens/Detail-Wait/DetailWaitViewController.swift
> +    // FIXME: - 나가기 테스트 해야함
아하.. 제가 방이라도 만들어볼까요?

2023-04-22 09:01 UTC, YoonAh-dev commented on Manito/Manito/Screens/Detail-Wait/View/DetailWaitView.swift
> +    private let imgNiView: UIImageView = {
그냥 저희 앱 캐릭터고 한 마리만 나오니깐 이건 어떤가요. characterImageView는 어떤가요?

2023-04-22 09:22 UTC, YoonAh-dev commented on Manito/Manito/Screens/Detail-Wait/View/DetailWaitView.swift
> +    func showAlert(title: String, message: String)
### 🙇‍♂️애플 도큐먼트에 나오는 Delegate 메소드들을 참고해주시면 됩니다.🙇‍♂️

> Delegate 메소드들은 동사로 시작하지 않고 대부분 명사로 시작합니다.

해당 명사는 **델리게이트의 이름**을 담고 있는 편입니다. 예를 들어서 UITableViewDelegate 같은 거요.
UITableViewDelegate 안에 있는 Delegate 메소드 이름은 이런 형식을 가집니다. 
```swift
func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int { }
``` 
TableViewDelegate라서 tableView를 메소드 명으로 시작하는 겁니다.

> 명사 뒤에 어떤일이 벌어지는지 적혀있습니다. 

1. 메소드 네이밍으로 적혀있는 경우도 있고 -> `tableViewDidEndMultipleSelectionInteraction(_:)`
2. 매개변수로 적혀있는 경우도 있습니다. -> `tableView(_:canMoveRowAt:)`

<br>

이렇게 네이밍을 하는 이유는 저도 자세하게는 모르고 더 알아봐야겠지만, `어떤 컴포넌트에서 어떤 일이 일어났을 때 어떤 행동을 한다.` 라는 문장이 있을 때 
* `어떤 컴포넌트에서 어떤 일이 일어났을 때` 까지는 위임을 해줄 부분에서 하는 일이고 
* `어떤 행동을 한다` 는 위임받을 부분에서 해줄 것이니, 

☑️ `어떤 컴포넌트에서 어떤 일이 일어났을 때`를 네이밍으로 하는 느낌입니다. 

위의 TableView Delegate에 있는 메소드를 예를 들어서 설명해드리자면, 

`[어떤 컴포넌트]` 에서 `[어떤 일이 일어났을 때]`
`[TableView]` 에서 `[Row를 움직일 수 있을 때(움직일 때)]` 

-> **`tableView(_:canMoveRowAt:)`**

<br>

이렇게 생각하고 네이밍을 하면 네이밍할 때 조금 더 편하지 않을까 생각이 듭니다. 그래서 startManitto도 [시작 버튼]에서 [터치(탭)가 일어났을 때] 니깐, startButtonDidTap 이런식으로 네이밍을 해주시면 되지 않을까 싶습니다.

2023-04-25 08:14 UTC, MMMIIIN commented on Manito/Manito/Screens/Detail-Wait/DetailWaitViewController.swift
> +    // FIXME: - 나가기 테스트 해야함
감사합니다! 테스트 완료했습니다 잘 되네용
[7620894](https://github.com/DeveloperAcademy-POSTECH/MC2-Team5-Firefighter/pull/444/commits/7620894c903033308165e6640b29c4548b16a098)

2023-04-25 09:58 UTC, dangsal commented on Manito/Manito/Screens/Detail-Wait/View/DetailWaitView.swift
> +    func configureLayout(room: Room) {
p2;

`configureLayout` 이라는 네이밍은 레이아웃을 잡는 함수 같아서 
`updateUI` 나 `bindingData` 나 
조금 다른 네이밍이 어떨까 생각합니다!

2023-04-28 05:20 UTC, YoonAh-dev commented on Manito/Manito/Screens/Detail-Wait/View/DetailWaitView.swift
> +        cell.textLabel?.font = .font(.regular, ofSize: 17)
p1;

cell에서 사용되는 `textLabel`가 deprecated 된 걸로 압니다. 확인 한 번 부탁드릴게요!

<img width="736" alt="스크린샷 2023-04-28 오후 2 20 04" src="https://user-images.githubusercontent.com/55099365/235060697-8ba5554b-c46d-4acc-b7f1-249d694d407b.png">

2023-04-28 05:30 UTC, YoonAh-dev commented on Manito/Manito/Screens/Detail-Wait/View/DetailWaitView.swift
> +extension DetailWaitView: UITableViewDataSource {
p5;

셀에 들어가는 데이터를 관리하고 셀을 제공하기 위한 메소드가 있는 UITableView가 데이터를 보여주는 일만 하기 때문에 UITableViewDataSource가 대신 데이터를 관리하는 일을 하고 있습니다.

따라서, UITableViewDataSource를 extension하는 걸 DetailWaitView가 아닌 DetailWaitViewController가 해도 괜찮지 않을까요? 

그러면 userArray를 굳이 View 내부로 들여오지 않고 Controller에서 관리할 수 있지 않을까요?

저도 DataSource에 위치는 계속 고민하고 있는 부분이라서 굳이 Controller로 옮기지 않으셔도 되지만 어떻게 생각하시는지는 궁금합니다. 👀💭

2023-04-28 05:43 UTC, YoonAh-dev commented on Manito/Manito/Screens/Detail-Wait/View/DetailWaitView.swift
> +            self?.delegate?.didTapCodeCopyButton(invitationCode: invitationCode)
p1;

code를 configureLayout 메소드에서 받아서 사용하는 것 같은데, 어차피 코드를 Toast해주는게 ViewController라면 View로 Code 데이터를 보내지 말고 ViewController에서 저장해서 사용해도 되지 않을까요?

2023-04-28 05:56 UTC, YoonAh-dev commented on Manito/Manito/Screens/Detail-Wait/View/DetailWaitView.swift
> +        self.setupTitleViewGesture(isAdmin)
p5;

이런 식으로 정리해볼 수 있지 않을까 싶어서, 코드 정리를 해보았습니다.

```swift
    func updateDetailWaitView(with room: Room) {
        guard let title = room.roomInformation?.title,
              let state = room.roomInformation?.state,
              let dateRange = room.roomInformation?.dateRange,
              let isStart = room.roomInformation?.isStart,
              let admin = room.admin
        else { return }

        self.setupTitleViewData(title: title, state: state, dateRange: dateRange)
        self.setupRelatedViews(of: admin, isStart)

        self.configureStartButton(room.canStart)
        self.configureUserCountLabel(userCount: room.userCount)
    }

    private func setupTitleViewData(title: String, state: String, dateRange: String) {
        self.titleView.setStartState(state: state)
        self.titleView.setupLabelData(title: title, dateRange: dateRange)
    }

    private func setupRelatedViews(of userStatus: Bool, _ isStart: Bool) {
        self.showStartButtonForAdmin(userStatus)
        self.setExitButtonMenu(userStatus)
        self.showAlertWhenPastDate(userStatus, isStart: isStart)
        self.setupTitleViewGesture(userStatus)
    }

    private func configureUserCountLabel(userCount: String) {
        self.userCountLabel.text = userCount
    }
```

관련 있는 부분들만 묶어서 정리해봤습니다. 
옵셔널 바인딩도 관련 함수에 들어가서 하고 싶은데, 그러면 너무 이해하기 어려울까봐 바인딩 부분은 놔뒀습니다. 옵셔널 바인딩을 관련 함수에서 하고 싶은 이유는 옵셔널 바인딩을 여러개 해두면 하나라도 값이 들어오지 않았을 때 return으로 메소드를 빠져나가게 되는데, 현재 상태로는 하나라도 값이 잘못들어오면 잘 들어오는 다른 값들도 화면에 올라가지 않아서 그렇습니다. 또한, 디버깅 시에 어떤 값에 문제가 생겼는지 확인하기 어렵습니다. 따라서, 가능하다면 관련 메소드 안에 들어가서 옵셔널 바인딩을 해줬으면 하네용.

일단 관련 있는 것끼리 묶어두긴 했지만 userStatus를 사용하는 부분은 어떤식으로 configuration를 잡을 지 더 생각해보면 좋을 것 같습니다. 

++) code, userArray는 다른 코멘트와 관련해서 일단 빼서 코드를 정리했습니다. 🙏

2023-04-28 05:58 UTC, YoonAh-dev commented on Manito/Manito/Screens/Detail-Wait/View/DetailWaitView.swift
> +    // MARK: - func
p4;

private, internal 함수가 섞여있어서 코드를 볼 때 어려움이 조금 있습니다. 
private과 internal 함수가 잘 정렬되어 있으면 좋겠습니다.!

2023-05-04 04:17 UTC, MMMIIIN commented on Manito/Manito/Screens/Detail-Wait/View/DetailWaitView.swift
> +    func configureLayout(room: Room) {
오호 그러네요!
`bind` 는 어떨까요??

2023-05-04 05:18 UTC, MMMIIIN commented on Manito/Manito/Screens/Detail-Wait/View/DetailWaitView.swift
> +extension DetailWaitView: UITableViewDataSource {
음... ViewController로 갔을 때 해당 UITableView의 데이터를 넣어주는게 조금 애매해집니다.
네트워크 통신은 ViewController에서 진행되고 해당 값(Room)을 View로 넘겨주는데, 그 과정에서 UITableView의 데이터인 UserArray는 따로 빼서 넘겨주지 않고 ViewController에서 할당하는게 애매한 것 같습니다...
View에서 자리잡고 있는것도 크게 어색하지 않아서 현재 방법이 괜찮다고 생각이 드네요!

2023-05-04 05:23 UTC, MMMIIIN commented on Manito/Manito/Screens/Detail-Wait/View/DetailWaitView.swift
> +            self?.delegate?.didTapCodeCopyButton(invitationCode: invitationCode)
어머? 그러네요..?? 
수정하겠습니다! 감사합니다 ^________^

2023-05-04 05:59 UTC, MMMIIIN commented on Manito/Manito/Screens/Detail-Wait/View/DetailWaitView.swift
> +    func showAlert(title: String, message: String)
수정했습니다! 근데 present되는 함수의 네이밍은 어떻게 해야할지 몰라 그대로 뒀습니다..!

[b969c01](https://github.com/DeveloperAcademy-POSTECH/MC2-Team5-Firefighter/pull/444/commits/b969c01ff6388ff5c95d750b0925f2f1d592a281)

2023-05-04 06:06 UTC, MMMIIIN commented on Manito/Manito/Screens/Detail-Wait/View/DetailWaitView.swift
> +        cell.textLabel?.font = .font(.regular, ofSize: 17)
오! 몰랐네요 덕분에 하나 알아갑니다 감사합니다!
[4f718ef](https://github.com/DeveloperAcademy-POSTECH/MC2-Team5-Firefighter/pull/444/commits/4f718efe8a6ca5a4ad70d04c592a9be164801625)

참고 : https://medium.com/geekculture/modern-configurations-for-cells-and-views-after-ios-14-0-33b5c82ac448

2023-05-04 06:07 UTC, MMMIIIN commented on Manito/Manito/Screens/Detail-Wait/View/DetailWaitView.swift
> +        self.setupTitleViewGesture(isAdmin)
감사합니다! 덕분에 조금 더 이해하기 편한 코드가 되었네요! ^__________^
[21b321d](https://github.com/DeveloperAcademy-POSTECH/MC2-Team5-Firefighter/pull/444/commits/21b321da769951a2a8b45c67e379014367f2bd88)

2023-05-04 06:07 UTC, MMMIIIN commented on Manito/Manito/Screens/Detail-Wait/View/DetailWaitView.swift
> +    // MARK: - func
주석은 따로 사용하지 않았고, private internal 순으로 정렬했습니다!
[d290816](https://github.com/DeveloperAcademy-POSTECH/MC2-Team5-Firefighter/pull/444/commits/d290816237050d0a666c03d4c01c95d46bfd2fc8)

2023-05-10 00:40 UTC, dangsal commented on Manito/Manito/Screens/Detail-Wait/View/DetailWaitView.swift
> +//    }
p1;

주석처리가 되어있어요!! 변경 부탁드려요~

2023-05-10 00:48 UTC, dangsal commented on Manito/Manito/Screens/Detail-Wait/View/DetailWaitView.swift
> +    }
p5;

`setExitButtonMenu` 함수에서는 isAdmin을 바로 조건문에 걸어 처리하시고
`showAlertWhenPastDate` 함수에서는 isAdmin을 type으로 나눈후 type을 switch문으로 처리하셨는데 하나의 방식으로 합치면 어떨까 생각합니다~

저는 `showAlertWhenPastDate` 함수처럼 하는게 더 읽기 좋을거라고 생각해요~!

2023-05-10 01:04 UTC, dangsal commented on Manito/Manito/Screens/Detail-Wait/View/DetailWaitView.swift
> +    func showAlert(title: String, message: String)
editButtonDidTap 이런건 별로인가요.?

2023-05-10 02:31 UTC, YoonAh-dev commented on Manito/Manito/Screens/Detail-Wait/View/DetailWaitView.swift
> +    func showAlert(title: String, message: String)
@MMMIIIN 
저도 호야가 말해주신 것처럼 하면 될 것 같아요! 다른 메서드 네이밍한 것과 동일하게 하면 되지 않을까요?

2023-05-10 14:55 UTC, MMMIIIN commented on Manito/Manito/Screens/Detail-Wait/View/DetailWaitView.swift
> +    private let imgNiView: UIImageView = {
뒤늦게 확인했네요.. 반영완료했습니다!
[f29d6dc](https://github.com/DeveloperAcademy-POSTECH/MC2-Team5-Firefighter/pull/444/commits/f29d6dc06827894eeef2c1bff5874e982402b05a)

2023-05-10 14:56 UTC, MMMIIIN commented on Manito/Manito/Screens/Detail-Wait/View/DetailWaitView.swift
> +    func showAlert(title: String, message: String)
두 커밋에 걸쳐 수정했습니다! ^__________^
[ff7956e](https://github.com/DeveloperAcademy-POSTECH/MC2-Team5-Firefighter/pull/444/commits/ff7956ec181562bbe09d3f833de186176a0233b1)
[6041202](https://github.com/DeveloperAcademy-POSTECH/MC2-Team5-Firefighter/pull/444/commits/60412028f17d8c528d50fbb9e51c4c9154fe21b5)

2023-05-10 15:02 UTC, MMMIIIN commented on Manito/Manito/Screens/Detail-Wait/View/DetailWaitView.swift
> +    }
[여기](https://github.com/DeveloperAcademy-POSTECH/MC2-Team5-Firefighter/pull/444/commits/60412028f17d8c528d50fbb9e51c4c9154fe21b5) 커밋에서 아래 `showAlertWhenPastDate`함수의 형식은 조금 달라졌지만, 리뷰 남겨주신 부분에 대해 동의해서 `setExitButtonMenu`이 함수에 적용했습니다!

[1d842ff](https://github.com/DeveloperAcademy-POSTECH/MC2-Team5-Firefighter/pull/444/commits/1d842ff17ce272aee75be1ca1301d140537d12de)

2023-05-12 12:27 UTC, dangsal approved these changes
좋습니다! 수고하셨습니다!

2023-05-14 13:57 UTC, YoonAh-dev approved these changes
수고하셨습니다!

2023-05-14 14:42 UTC, merged